version: "3.9"

services:
  api:
    build: .
    container_name: crm-pet-system
    ports:
      - "3000:3000"
    env_file:
      - .env         # dotenv пробрасывается внутрь контейнера
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    # При старте контейнера сначала выполняем миграции, затем запускаем NestJS

  db:
    image: postgres:16-alpine
    container_name: crm-pet-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - crm_pet_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  crm_pet_pg:
