version: "3.9"

services:
  api:
    build: .
    container_name: crm-pet-system
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:01072011Ba@db:5432/crm-system?schema=public
      POSTGRES_DB: crm-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01072011Ba
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: crm-pet-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - crm_pet_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  crm_pet_pg:
