global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crm-business-system'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:3010'
        labels:
          app: 'crm-business-system'
